# Tensor(张量)
Tensor类似于NumPy的ndarrays, 同时Tensors可以使用GPU计算。


In [26]:
import torch

构造一个5×3矩阵，不初始化。

In [27]:
x = torch.empty(5,3)
print(x)

tensor([[ 0.0000e+00,  4.6566e-10, -4.3723e+12],
        [-2.0005e+00,  1.1210e-44,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])


构造一个随机初始化的矩阵：

In [28]:
x = torch.rand(5,3)
print(x)

tensor([[0.0735, 0.0205, 0.3902],
        [0.9245, 0.3833, 0.8828],
        [0.9404, 0.9217, 0.5041],
        [0.0300, 0.1645, 0.4036],
        [0.3398, 0.6502, 0.7032]])


构造一个矩阵全为0，而且数据类型是long.

In [29]:
x = torch.zeros(5,3,dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


构造一个张量，直接输用数据：

In [30]:
x = torch.tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


创建一个tensor基于已经存在tensor。

In [31]:
x = x.new_ones(5,3,dtype=torch.double) # dtype=设置创建的tensor类型
print(x)
print(x.size())
# 用x创建一个和它维度相同的随机数组成的tensor
x = torch.randn_like(x,dtype=torch.float)
print(x)
print(x.size())

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
torch.Size([5, 3])
tensor([[ 0.9915, -1.5255, -0.0252],
        [ 1.4588, -0.4203, -0.0878],
        [-0.0774, -1.6134, -1.6982],
        [-0.8384, -2.4396, -0.2287],
        [ 0.6545,  1.0417,  2.1954]])
torch.Size([5, 3])


**注意**：torch.Size是一个元组，所以它支持左右的元组操作。  

## 操作
### 加法
#### 方式1

In [32]:
y =torch.rand(5,3)
print(x+y)

tensor([[ 1.1847, -0.7449,  0.6715],
        [ 2.3694, -0.0964,  0.4175],
        [ 0.1073, -0.7825, -0.8827],
        [ 0.0565, -2.0752, -0.1193],
        [ 1.4502,  1.7577,  2.5548]])


#### 方式2

In [33]:
print(torch.add(x,y))

tensor([[ 1.1847, -0.7449,  0.6715],
        [ 2.3694, -0.0964,  0.4175],
        [ 0.1073, -0.7825, -0.8827],
        [ 0.0565, -2.0752, -0.1193],
        [ 1.4502,  1.7577,  2.5548]])


#### 方式3
提供一个tensor作为参数保存结果

In [34]:
result = torch.empty(5,3)
torch.add(x,y,out=result)
print(result)

tensor([[ 1.1847, -0.7449,  0.6715],
        [ 2.3694, -0.0964,  0.4175],
        [ 0.1073, -0.7825, -0.8827],
        [ 0.0565, -2.0752, -0.1193],
        [ 1.4502,  1.7577,  2.5548]])


#### 方式4

In [35]:
y.add_(x)
print(y)

tensor([[ 1.1847, -0.7449,  0.6715],
        [ 2.3694, -0.0964,  0.4175],
        [ 0.1073, -0.7825, -0.8827],
        [ 0.0565, -2.0752, -0.1193],
        [ 1.4502,  1.7577,  2.5548]])


**注意**：任何使张量发生变化的操作都有一个前缀。
### 索引/切片

In [36]:
print(x[:,1])

tensor([-1.5255, -0.4203, -1.6134, -2.4396,  1.0417])


#### 改变大小
如果你想要的改变一个tensor的大小或者形状，你可以使用torch.view()

In [37]:
x = torch.randn(4,4) # randn是均匀分布随机 rand是纯随机
y = x.view(16)
z = x.view(-1,8) # 这里设置-1就表示这个值依赖于8  16/8=2 因此实际为2
print(x.size(),y.size(),z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


### 取值
如果你有一个元素tensor，使用.item()来获得这个value。

In [38]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.5105])
0.5104895830154419
