# 什么是PyTorch？  
## 张量(Tensors)
Tensors类似于numpy中的ndarrays，同时Tensors可以使用GPU计算。

In [1]:
import torch # 调用pytorch

构造一个5×3的矩阵，不初始化。

In [2]:
x = torch.empty(5,3) # shap=(5,3)
print(x)

tensor([[1.2120e+25, 1.3556e-19, 1.8567e-01],
        [1.9492e-19, 7.5553e+28, 5.2839e-11],
        [1.7589e+22, 2.5038e-12, 1.1362e+30],
        [7.1547e+22, 4.5828e+30, 3.2537e+12],
        [3.2608e-12, 1.1632e+33, 5.6003e-02]])


构造一个随机初始化的矩阵

In [3]:
x = torch.rand(5,3) # 随机初始化，大小为5×3
print(x)

tensor([[0.3769, 0.3446, 0.5225],
        [0.8381, 0.8051, 0.7474],
        [0.9907, 0.8126, 0.3824],
        [0.9402, 0.2669, 0.4212],
        [0.6137, 0.8645, 0.4996]])


构造一个矩阵全为0，而且数据类是long

In [4]:
x = torch.zeros(5,3,dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


直接使用数据来创建一个tensor

In [5]:
x = torch.tensor([5,5,3])
print(x)

tensor([5, 5, 3])


创建一个tensor基于已经存在tensor

In [6]:
x = x.new_ones(5,3,dtype=torch.double)
print(x)
y = x.new_zeros(5,6,dtype=torch.double)
print(y)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]], dtype=torch.float64)


获取它的维度信息:

In [7]:
print(x.size())
print(y.size())

torch.Size([5, 3])
torch.Size([5, 6])


需要注意的是torch.size是一个元组，所以它支持左右的元组操作。
### 加法运算
第一种方式:

In [8]:
y = torch.rand(5,3)
print(y)
print(x+y)

tensor([[0.7041, 0.0379, 0.8153],
        [0.9673, 0.8777, 0.5551],
        [0.0911, 0.9323, 0.3121],
        [0.4540, 0.4334, 0.8223],
        [0.8973, 0.3472, 0.6402]])
tensor([[1.7041, 1.0379, 1.8153],
        [1.9673, 1.8777, 1.5551],
        [1.0911, 1.9323, 1.3121],
        [1.4540, 1.4334, 1.8223],
        [1.8973, 1.3472, 1.6402]], dtype=torch.float64)


第二种方式:

In [10]:
print(torch.add(x,y))

tensor([[1.7041, 1.0379, 1.8153],
        [1.9673, 1.8777, 1.5551],
        [1.0911, 1.9323, 1.3121],
        [1.4540, 1.4334, 1.8223],
        [1.8973, 1.3472, 1.6402]], dtype=torch.float64)


提供一个输出tensor作为参数:

In [12]:
result = torch.empty(5,3)
torch.add(x,y,out=result) # 等价于 result = torch.add(x+y)
print(result)

tensor([[1.7041, 1.0379, 1.8153],
        [1.9673, 1.8777, 1.5551],
        [1.0911, 1.9323, 1.3121],
        [1.4540, 1.4334, 1.8223],
        [1.8973, 1.3472, 1.6402]])


第三种方式:使用in-place

In [13]:
y.add_(x)
print(y)

tensor([[1.7041, 1.0379, 1.8153],
        [1.9673, 1.8777, 1.5551],
        [1.0911, 1.9323, 1.3121],
        [1.4540, 1.4334, 1.8223],
        [1.8973, 1.3472, 1.6402]])


需要注意的是这样会使得到y发生改变。
### 切片索引
你也可以使用类似于numpy的索引操作

In [14]:
print(x[:,:1])

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [1.]], dtype=torch.float64)


### 改变大小
如果你想改变一个tensor的大小，可以使用torch.view()

In [15]:
x = torch.randn(4,4)
y = x.view(16) # 拉成一个一维数组了
z = x.view(-1,8) # 2×8
print(x,y,z)

tensor([[-2.0162,  0.4423, -0.3467, -0.0440],
        [ 0.2886,  0.0516, -0.9108, -0.0136],
        [ 1.8925, -0.8485,  0.3412,  0.3256],
        [-0.5905,  1.9149, -1.0524,  0.6172]]) tensor([-2.0162,  0.4423, -0.3467, -0.0440,  0.2886,  0.0516, -0.9108, -0.0136,
         1.8925, -0.8485,  0.3412,  0.3256, -0.5905,  1.9149, -1.0524,  0.6172]) tensor([[-2.0162,  0.4423, -0.3467, -0.0440,  0.2886,  0.0516, -0.9108, -0.0136],
        [ 1.8925, -0.8485,  0.3412,  0.3256, -0.5905,  1.9149, -1.0524,  0.6172]])


# 获取tensor的值

In [19]:
x = torch.randn(2,3)
print(x)
print(x[1][2].item())

tensor([[ 0.1411,  0.6976, -0.1832],
        [-2.5372,  0.6078, -1.4216]])
-1.4216125011444092
